[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$du7de2/NWSsF4DxnrNUaow$HBY4dXg.i5Xa7vf1KC8IUvMQVnFsYfurX4Kh/04WNmmtZYFpBW29caCC2Vq.Oq8pzsngwlcEfCDSmhsLbPqXwg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
logfile = /var/log/odoo/odoo.log
log_level = info
workers = 2

